### ISSUE TITLE
sshd fails in MAC config line

### ISSUE THREAD

**Issue by jankatins** [debops/debops#238]
I installed sshd via debops on my local laptop. I didn't set any sshd related config option in my vars. `debops`now fails with this message:

```
RUNNING HANDLER [debops.sshd : Test sshd configuration and restart] **********************************************************************************************************************************
fatal: [littlebottom2]: FAILED! => {"changed": true, "cmd": ["sshd", "-t"], "delta": "0:00:00.004924", "end": "2018-03-19 00:28:30.666923", "msg": "non-zero return code", "rc": 255, "start": "2018-03-19 00:28:30.661999", "stderr": "/etc/ssh/sshd_config line 18: Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-ripemd160'.", "stderr_lines": ["/etc/ssh/sshd_config line 18: Bad SSH2 mac spec 'hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-ripemd160'."], "stdout": "", "stdout_lines": []}
```

I'm running debian unstable with this ssh packages:

```
λ dpkg -l |grep ssh
[...]  
ii  openssh-client                          1:7.6p1-4                           amd64        secure shell (SSH) client, for secure access to remote machines
ii  openssh-server                          1:7.6p1-4                           amd64        secure shell (SSH) server, for secure access from remote machines
```

As far as I understand the problem, my sshd version needs a new versioned list of MACs, similar to this: https://github.com/dev-sec/ansible-ssh-hardening/pull/139

**Comment by jankatins** [comment]
Adding this in a vars file let it run throught, but now fails on a different line:

```
sshd__macs_map:
  '7.6': [ 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com',
           'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256' ]
```

```
RUNNING HANDLER [debops.sshd : Test sshd configuration and restart] **********************************************************************************************************************************
fatal: [littlebottom2]: FAILED! => {"changed": true, "cmd": ["sshd", "-t"], "delta": "0:00:00.016920", "end": "2018-03-19 00:49:01.285982", "msg": "non-zero return code", "rc": 255, "start": "2018-03-19 00:49:01.269062", "stderr": "/etc/ssh/sshd_config line 21: Deprecated option UsePrivilegeSeparation\r\nMissing privilege separation directory: /run/sshd", "stderr_lines": ["/etc/ssh/sshd_config line 21: Deprecated option UsePrivilegeSeparation", "Missing privilege separation directory: /run/sshd"], "stdout": "", "stdout_lines": []}
```

**Comment by drybjed** [comment]
The `UsePrivilegeSeparation` was deprecated as an "option", this is now mandatory. This could be handled by a `version_compare()` check in the config file. Can you check if `sshd` starts correctly if you remove this option from the config file, or is there something else needed?

New list of MACs for the newer version sounds good, do you want to add it via a PR?

**Comment by jankatins** [comment]
Yes, it comes up when I remove that line completely from the sshd_config file.

**Comment by drybjed** [comment]
Great, I'll try to update the role before the next release then. Thanks for the bug report.

**Comment by jankatins** [comment]
Thanks for your work on this :-)

**Comment by drybjed** [comment]
@jankatins You set a new list of MACs, however `debops.sshd` has already list of MACs without `hmac-rpemd160`, based on the Mozilla guidelines:
```
  # Source: https://wiki.mozilla.org/Security/Guidelines/OpenSSH
    '6.5': [ 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com',
             'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256',
             'umac-128@openssh.com' ]
```
I cannot find any information through Google search about `umac-128@openssh.com` resulting in issues with SSH server. I'll fix the privilege separation first and let you check if the issue with MACs persists.

**Comment by drybjed** [comment]
The issue with privilege separation option should be resolved by https://github.com/debops/debops/pull/240.

**Comment by jankatins** [comment]
Will try tonight. Thanks!

**Comment by jankatins** [comment]
done: still only worked with this in a vars file (tried with and without):

```yaml
sshd__macs_map:

  '7.6': [ 'hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com',
           'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256' ]
```

**Comment by drybjed** [comment]
@jankatins Thanks for testing. I wonder what changed in the Debian package that doesn't let `sshd` work with `umac-128@openssh.com` MAC... Any ideas? I'm going to add it to the role, of course, but it would be nice to have some basis for why it's like this...

**Comment by drybjed** [comment]
This issue should be fixed by https://github.com/debops/debops/pull/254. @jankatins, can you check and confirm?

**Comment by jankatins** [comment]
Something still seems to be broken here: my config ends up with this:

```
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-ripemd160
```

**Comment by drybjed** [comment]
It looks like the version of the SSH server package is incorrectly detected. What do you get when you run:
```
dpkg-query -W -f="\${Version}\n" "openssh-server" | sed -re "s/^.*:([0-9]+\.[0-9]+).*/\1/"
```
On Debian Stretch, my output looks like:
```
7.4
```

**Comment by jankatins** [comment]
There is still a problem:

* The dict is differently sorted than in the definition (probably a python dict problem: only in py3.7, the input order is guaranteed -> `for key, value in sshd__macs_map|dictsort(reverse=true)` should take care of that)
* But it still adds all mac, even the one form 6.0 to the list:

```jinja

{% endif %}
{% set sshd__tpl_macs = [] %}
{% set sshd__tpl_macs_match = False %}
{% for key, value in sshd__macs_map|dictsort(reverse=true) %}
# {{ key }} {{ value }}
# before setting:: {{sshd__tpl_macs_match}}
{%   if not sshd__tpl_macs_match and
        sshd__register_version.stdout|d() and
        sshd__register_version.stdout | version_compare(key, '>=') %}
        # versions: {{sshd__register_version.stdout}}, {{ key }}
{%     set sshd__tpl_macs_match = True %}
        # after setting:: {{sshd__tpl_macs_match}}
{%     for element in value %}
{%       set _ = sshd__tpl_macs.append(element) %}
{%     endfor %}
{%   endif %}
{% endfor %}
{% set sshd__tpl_macs = (sshd__tpl_macs + sshd__macs_additional) | unique %}
{% if sshd__tpl_macs and sshd__paranoid|bool %}
MACs {{ ([ sshd__tpl_macs|first ] + sshd__macs_additional) | unique | join(",") }}
```

Ended up as 

```
# 7.6 ['hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256']
# before setting:: False
        # versions: 7.6, 7.6
        # after setting:: True
# 6.5 ['hmac-sha2-512-etm@openssh.com', 'hmac-sha2-256-etm@openssh.com', 'umac-128-etm@openssh.com', 'hmac-sha2-512', 'hmac-sha2-256', 'umac-128@openssh.com']
# before setting:: False
        # versions: 7.6, 6.5
        # after setting:: True
# 6.0 ['hmac-sha2-512', 'hmac-sha2-256', 'hmac-ripemd160']
# before setting:: False
        # versions: 7.6, 6.0
        # after setting:: True
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com,hmac-ripemd160
```

-> So the iteration doesn't break after the first find

So my patch above probably only worked because it replaced the whole dict, not added to it and therfore the 6.0 items were not added.

**Comment by jankatins** [comment]
This works:

```jinja
{% set sshd__tpl_macs = [] %}
{# workaround for jinja not beeing able to overwrite a variable inside the loop #}
{% set sshd__tpl_macs_match = [] %}
{% for key, value in sshd__macs_map|dictsort(reverse=true) %}
{%   if not sshd__tpl_macs_match and
        sshd__register_version.stdout|d() and
        sshd__register_version.stdout | version_compare(key, '>=') %}
{%     if sshd__tpl_macs_match.append(True) %}{% endif %} {# more workaround... #}
{%     for element in value %}
{%       set _ = sshd__tpl_macs.append(element) %}
{%     endfor %}
{%   endif %}
{% endfor %}
{% set sshd__tpl_macs = (sshd__tpl_macs + sshd__macs_additional) | unique %}
{% if sshd__tpl_macs and sshd__paranoid|bool %}
MACs {{ ([ sshd__tpl_macs|first ] + sshd__macs_additional) | unique | join(",") }}
```

-> Workaround from here: https://stackoverflow.com/questions/9486393/jinja2-change-the-value-of-a-variable-inside-a-loop

**Comment by drybjed** [comment]
Yes, I thought that could be a workaround, it's common in DebOps. Do you want to make a PR?

**Comment by jankatins** [comment]
done: https://github.com/debops/debops/pull/259 Please tell me if I have to change something...

**Comment by drybjed** [comment]
@jankatins You could update the PR with the suggested change. :-)
